### ISSUE TITLE
Featured entry daet brokken

### ISSUE THREAD

**Issue by griceylipper** [ShetlandJ/shetland_wirds#81]
Shaetlan:
![image](https://user-images.githubusercontent.com/6740627/181610867-519525ae-19b0-426d-ba88-a8a14448556a.png)

English:
![image](https://user-images.githubusercontent.com/6740627/181611325-9f384e65-f07f-4923-a611-e30cac7db982.png)

**Comment by ShetlandJ** [comment]
Fixed
