### ISSUE TITLE
Unexpected behavior wi results & page numbers, an gyaan tae da neest page whin saerchin fir wirds

### ISSUE THREAD

**Issue by griceylipper** [ShetlandJ/shetland_wirds#84]
![image](https://user-images.githubusercontent.com/6740627/181617720-2a4d76af-0e08-4422-82e5-3d324f3e75dd.png)
De'r onnly 5 results at comes up, but it repoarts da full size o da database

Dan if you try an ging til da neest page, you git dis:
![image](https://user-images.githubusercontent.com/6740627/181617982-bc43d009-cd48-4caf-8177-bc851dc2f3db.png)
![image](https://user-images.githubusercontent.com/6740627/181618093-cf7c9af6-b799-4bf7-bec0-1c411ecae0f4.png)

**Comment by ShetlandJ** [comment]
@griceylipper disll be as a result of my infrastructure upgrade. I Kaen da fix

**Comment by ShetlandJ** [comment]
Fixed
